<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>4_catch문과 finally문</title>
</head>
<body>
  <script>
    /* 
      ● async, await - 프로미스 객체가 rejected 상태가 되는 경우
    */
    /* 
      이전에 프로미스 체이닝에서는  
      프로미스 객체가 rejected 상태가 될 때를 대비해서 catch메소드를 사용했다.

      * async/await 구문에서는 try...catch 문을 사용하면 된다.


      async function fetchAndPrint() {
        const response = await fetch('https://jsonplaceholder.typicode.commm/users')
        const result = await response.text();
        console.log(result);
      }

      fetchAndPrint(); 

      위 코드를 고치면
    */

      
      async function fetchAndPrint() {
        try {
          const response = await fetch('https://jsonplaceholder.typicode.commm/users')
          const result = await response.text();
          console.log(result);
        } catch (error) {
          console.log(error);
        } finally {
          console.log('exit');
        }
      } 
      fetchAndPrint(); //TypeError: Failed to fetch

    /* 
      [catch]
      try 블록 안에서 await이 앞에 붙어있는 프로미스 객체들 중 rejected 상태가 되는 것이 생기면
      그 순간 코드의 실행 흐름이 catch문으로 넘어오게 된다.

      그리고
      catch (error) {
        console.log(error);
      }
      에서의 (error)파라미터로 프로미스 객체의 작업실패정보가 넘어온다.


      [finally]
      - finally문도 프로미스 체이닝때 배운 finally 메소드와 같은 기능을 가진다.
      - 항상 실행하고 싶은 코드가 있을 때 사용
    */
  </script>
</body>
</html>